### ISSUE TITLE
repo rename

### ISSUE THREAD

**Issue by superfunc** [ku-fpg/thrust-gen#10]
Mike and I have come together and decided on a name to replace the temporary thrust-gen name. We've gone with **ion** (all lowercase). The name comes from ion thrusters on rockets. @andygill when you get the chance, could you rename the repo?

**Comment by andygill** [comment]
Happy to change it. But first consider others using the same name

Links:
- http://en.wikipedia.org/wiki/Ion_(disambiguation)
-  https://github.com/krisnye/ion
- No one has http://ion-lang.org/

One alternative that I use is the Stan Lee approach: double barrel names. (Kansas Lava, Sun-roof, blank-canvas, story-board, ...) Though Stan uses alliteration more than we do.

Perhaps a pun on heavy ion, because Haskell starts with H?

Let me know, and I'll change the repo.

**Comment by superfunc** [comment]
After discussing it with Mike, we decided to stick with the original idea (**ion**)since it doesn't clash with anything on Hackage, which was our main concern. And the ion lang seems relatively insignificant (the irony of this coming from a guy who raves about using nim is not lost on me).

**Comment by superfunc** [comment]
ping @andygill

**Comment by andygill** [comment]
You want a rename?

**Comment by superfunc** [comment]
Yeah, I think only the admin can do it.

**Comment by andygill** [comment]
I'll do this tomorrow when we're in the same room.
